import type { AgentMessage } from "@earendil-works/pi-agent-core";
import { type ImageContent, type Message, type TextContent, type Usage, uuidv7 } from "@earendil-works/pi-ai";
import { randomUUID } from "crypto";
import {
	appendFileSync,
	type BigIntStats,
	closeSync,
	constants,
	createReadStream,
	existsSync,
	fstatSync,
	fsyncSync,
	linkSync,
	lstatSync,
	mkdirSync,
	openSync,
	readdirSync,
	readSync,
	realpathSync,
	renameSync,
	statSync,
	unlinkSync,
	writeFileSync,
} from "fs";
import { readdir, stat } from "fs/promises";
import { basename, dirname, join, parse, resolve } from "path";
import lockfile from "proper-lockfile";
import { createInterface } from "readline";
import { StringDecoder } from "string_decoder";
import { getAgentDir as getDefaultAgentDir, getSessionsDir } from "../config.ts";
import { canonicalizePath, normalizePath, resolvePath } from "../utils/paths.ts";
import {
	type BashExecutionMessage,
	type CustomMessage,
	createBranchSummaryMessage,
	createCompactionSummaryMessage,
	createCustomMessage,
} from "./messages.ts";

export const CURRENT_SESSION_VERSION = 3;

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	timestamp: string;
	cwd: string;
	parentSession?: string;
}

export interface NewSessionOptions {
	id?: string;
	parentSession?: string;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** Usage from the LLM call(s) that generated this summary, if available */
	usage?: Usage;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** Usage from the LLM call that generated this summary, if available */
	usage?: Usage;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

export type SessionNameOrigin = "human" | "automatic";

export interface SessionNameWriteOptions {
	origin?: SessionNameOrigin;
}

export interface SessionNameState {
	name: string | undefined;
	/** ID of the latest session_info entry, including an explicit clear. */
	entryId: string | undefined;
}

export type SessionNameWriteResult =
	| { written: true; entryId: string }
	| { written: false; currentState: SessionNameState };

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
	/** Optional provenance. Missing values from older writers are human/unknown. */
	origin?: SessionNameOrigin;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| SessionInfoEntry;

/** Raw file entry (includes header) */
export type FileEntry = SessionHeader | SessionEntry;

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
	/** Timestamp of the latest label change for this entry, if any */
	labelTimestamp?: string;
}

export interface SessionContext {
	messages: AgentMessage[];
	thinkingLevel: string;
	model: { provider: string; modelId: string } | null;
}

export interface SessionInfo {
	path: string;
	id: string;
	/** Working directory where the session was started. Empty string for old sessions. */
	cwd: string;
	/** User-defined display name from session_info entries. */
	name?: string;
	/** Path to the parent session (if this session was forked). */
	parentSessionPath?: string;
	created: Date;
	modified: Date;
	messageCount: number;
	firstMessage: string;
	allMessagesText: string;
}

export type ReadonlySessionManager = Pick<
	SessionManager,
	| "getCwd"
	| "getSessionDir"
	| "getSessionId"
	| "getSessionFile"
	| "getLeafId"
	| "getLeafEntry"
	| "getEntry"
	| "getLabel"
	| "getBranch"
	| "buildContextEntries"
	| "getHeader"
	| "getEntries"
	| "getTree"
	| "getSessionName"
	| "getSessionNameState"
>;

function createSessionId(): string {
	return uuidv7();
}

export function assertValidSessionId(id: string): void {
	if (!/^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$/.test(id)) {
		throw new Error(
			"Session id must be non-empty, contain only alphanumeric characters, '-', '_', and '.', and start and end with an alphanumeric character",
		);
	}
}

/** Generate a unique short ID (8 hex chars, collision-checked) */
function generateId(byId: { has(id: string): boolean }): string {
	for (let i = 0; i < 100; i++) {
		const id = randomUUID().slice(0, 8);
		if (!byId.has(id)) return id;
	}
	// Fallback to full UUID if somehow we have collisions
	return randomUUID();
}

/** Migrate v1 → v2: add id/parentId tree structure. Mutates in place. */
function migrateV1ToV2(entries: FileEntry[]): void {
	const ids = new Set<string>();
	let prevId: string | null = null;

	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 2;
			continue;
		}

		entry.id = generateId(ids);
		entry.parentId = prevId;
		prevId = entry.id;

		// Convert firstKeptEntryIndex to firstKeptEntryId for compaction
		if (entry.type === "compaction") {
			const comp = entry as CompactionEntry & { firstKeptEntryIndex?: number };
			if (typeof comp.firstKeptEntryIndex === "number") {
				const targetEntry = entries[comp.firstKeptEntryIndex];
				if (targetEntry && targetEntry.type !== "session") {
					comp.firstKeptEntryId = targetEntry.id;
				}
				delete comp.firstKeptEntryIndex;
			}
		}
	}
}

/** Migrate v2 → v3: rename hookMessage role to custom. Mutates in place. */
function migrateV2ToV3(entries: FileEntry[]): void {
	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 3;
			continue;
		}

		// Update message entries with hookMessage role
		if (entry.type === "message") {
			const msgEntry = entry as SessionMessageEntry;
			if (msgEntry.message && (msgEntry.message as { role: string }).role === "hookMessage") {
				(msgEntry.message as { role: string }).role = "custom";
			}
		}
	}
}

/**
 * Run all necessary migrations to bring entries to current version.
 * Mutates entries in place. Returns true if any migration was applied.
 */
function migrateToCurrentVersion(entries: FileEntry[]): boolean {
	const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
	const version = header?.version ?? 1;

	if (version >= CURRENT_SESSION_VERSION) return false;

	if (version < 2) migrateV1ToV2(entries);
	if (version < 3) migrateV2ToV3(entries);

	return true;
}

/** Exported for testing */
export function migrateSessionEntries(entries: FileEntry[]): void {
	migrateToCurrentVersion(entries);
}

/** Exported for compaction.test.ts */
export function parseSessionEntries(content: string): FileEntry[] {
	const entries: FileEntry[] = [];
	const lines = content.trim().split("\n");

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const entry = JSON.parse(line) as FileEntry;
			entries.push(entry);
		} catch {
			// Skip malformed lines
		}
	}

	return entries;
}

export function getLatestCompactionEntry(entries: SessionEntry[]): CompactionEntry | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		if (entries[i].type === "compaction") {
			return entries[i] as CompactionEntry;
		}
	}
	return null;
}

function getLatestSessionInfoEntry(entries: readonly FileEntry[]): SessionInfoEntry | undefined {
	for (let i = entries.length - 1; i >= 0; i--) {
		if (entries[i].type === "session_info") {
			return entries[i] as SessionInfoEntry;
		}
	}
	return undefined;
}

function buildEntryIndex(entries: SessionEntry[], byId?: Map<string, SessionEntry>): Map<string, SessionEntry> {
	if (byId) return byId;
	const index = new Map<string, SessionEntry>();
	for (const entry of entries) {
		index.set(entry.id, entry);
	}
	return index;
}

function buildSessionPath(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionEntry[] {
	const index = buildEntryIndex(entries, byId);
	let leaf: SessionEntry | undefined;
	if (leafId === null) {
		return [];
	}
	if (leafId) {
		leaf = index.get(leafId);
	}
	if (!leaf) {
		for (let i = entries.length - 1; i >= 0; i--) {
			if (entries[i].type !== "session_info") {
				leaf = entries[i];
				break;
			}
		}
	}
	if (!leaf) {
		return [];
	}

	const path: SessionEntry[] = [];
	let current: SessionEntry | undefined = leaf;
	while (current) {
		path.push(current);
		current = current.parentId ? index.get(current.parentId) : undefined;
	}
	path.reverse();
	return path;
}

function getSessionContextSettings(path: SessionEntry[]): Pick<SessionContext, "thinkingLevel" | "model"> {
	let thinkingLevel = "off";
	let model: { provider: string; modelId: string } | null = null;

	for (const entry of path) {
		if (entry.type === "thinking_level_change") {
			thinkingLevel = entry.thinkingLevel;
		} else if (entry.type === "model_change") {
			model = { provider: entry.provider, modelId: entry.modelId };
		} else if (entry.type === "message" && entry.message.role === "assistant") {
			model = { provider: entry.message.provider, modelId: entry.message.model };
		}
	}

	return { thinkingLevel, model };
}

/**
 * Project one selected session entry into LLM/runtime messages.
 * Plain custom entries are display/state entries and do not participate in context.
 */
export function sessionEntryToContextMessages(entry: SessionEntry): AgentMessage[] {
	if (entry.type === "message") {
		const message = entry.message;
		// Session files are parsed without validation; old versions, forks, or
		// hand-edited files can contain messages with null/missing content.
		if (
			(message.role === "user" || message.role === "assistant" || message.role === "toolResult") &&
			message.content == null
		) {
			return [{ ...message, content: [] }];
		}
		return [message];
	}
	if (entry.type === "custom_message") {
		return [
			createCustomMessage(entry.customType, entry.content ?? [], entry.display, entry.details, entry.timestamp),
		];
	}
	if (entry.type === "branch_summary" && entry.summary) {
		return [createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp)];
	}
	if (entry.type === "compaction") {
		return [createCompactionSummaryMessage(entry.summary, entry.tokensBefore, entry.timestamp)];
	}
	return [];
}

/**
 * Build the active, compaction-aware session entry list.
 *
 * This follows the current leaf path. If the path contains compaction entries,
 * the latest compaction is represented by the compaction entry itself, followed
 * by the kept entries starting at firstKeptEntryId and all entries after the
 * compaction entry. Older summarized entries are omitted.
 */
export function buildContextEntries(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionEntry[] {
	const path = buildSessionPath(entries, leafId, byId);
	let compaction: CompactionEntry | null = null;

	for (const entry of path) {
		if (entry.type === "compaction") {
			compaction = entry;
		}
	}

	if (!compaction) {
		return path;
	}

	const compactionIdx = path.findIndex((entry) => entry.id === compaction.id);
	if (compactionIdx < 0) {
		return path;
	}

	const contextEntries: SessionEntry[] = [compaction];
	let foundFirstKept = false;
	for (let i = 0; i < compactionIdx; i++) {
		const entry = path[i];
		if (entry.id === compaction.firstKeptEntryId) {
			foundFirstKept = true;
		}
		if (foundFirstKept) {
			contextEntries.push(entry);
		}
	}
	contextEntries.push(...path.slice(compactionIdx + 1));
	return contextEntries;
}

/**
 * Build the session context from entries using tree traversal.
 * If leafId is provided, walks from that entry to root.
 * Handles compaction and branch summaries along the path.
 */
export function buildSessionContext(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionContext {
	const path = buildSessionPath(entries, leafId, byId);
	const { thinkingLevel, model } = getSessionContextSettings(path);
	const messages = buildContextEntries(entries, leafId, byId).flatMap(sessionEntryToContextMessages);
	return { messages, thinkingLevel, model };
}

/**
 * Compute the default session directory for a cwd.
 * Encodes cwd into a safe directory name under ~/.pi/agent/sessions/.
 */
function getDefaultSessionDirPath(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const resolvedCwd = resolvePath(cwd);
	const resolvedAgentDir = resolvePath(agentDir);
	const safePath = `--${resolvedCwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`;
	return join(resolvedAgentDir, "sessions", safePath);
}

export function getDefaultSessionDir(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const sessionDir = getDefaultSessionDirPath(cwd, agentDir);
	if (!existsSync(sessionDir)) {
		mkdirSync(sessionDir, { recursive: true });
	}
	return sessionDir;
}

const SESSION_READ_BUFFER_SIZE = 1024 * 1024;
const SESSION_HEADER_READ_BUFFER_SIZE = 4096;
/**
 * Expensive transcript loads and name scans happen before acquiring this lock.
 * Lock callbacks only verify a scanned physical revision and commit one append
 * or atomic replacement, so synchronous scans cannot block heartbeat updates.
 */
const SESSION_FILE_LOCK_STALE_MS = 5 * 60 * 1000;
const SESSION_FILE_LOCK_RETRY_ATTEMPTS = 30;
const SESSION_REVISION_RETRY_ATTEMPTS = 30;

function resolveMissingPathThroughExistingAncestor(filePath: string): string {
	let ancestor = filePath;
	const missingParts: string[] = [];
	const root = parse(filePath).root;
	while (ancestor !== root) {
		try {
			const stats = lstatSync(ancestor);
			if (stats.isSymbolicLink()) {
				try {
					ancestor = realpathSync(ancestor);
				} catch (error) {
					throw new Error(`Session path alias does not resolve to an existing path: ${ancestor}`, {
						cause: error,
					});
				}
			}
			return join(canonicalizePath(ancestor), ...missingParts.reverse());
		} catch (error) {
			if (!(typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT")) throw error;
			missingParts.push(basename(ancestor));
			ancestor = dirname(ancestor);
		}
	}
	return join(root, ...missingParts.reverse());
}

function resolveSessionFileIdentity(sessionFile: string): string {
	const resolved = resolvePath(sessionFile);
	let lexical: ReturnType<typeof lstatSync>;
	try {
		lexical = lstatSync(resolved);
	} catch (error) {
		if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") {
			return resolveMissingPathThroughExistingAncestor(resolved);
		}
		throw error;
	}
	if (!lexical.isSymbolicLink()) return canonicalizePath(resolved);
	try {
		return realpathSync(resolved);
	} catch (error) {
		throw new Error(`Session file alias does not resolve to an existing file: ${resolved}`, { cause: error });
	}
}

interface SessionFileRevision {
	dev: bigint;
	ino: bigint;
	size: bigint;
	mtimeNs: bigint;
	ctimeNs: bigint;
}

class SessionFileRevisionMismatchError extends Error {
	constructor(sessionFile: string) {
		super(`Session file changed before transaction commit: ${sessionFile}`);
		this.name = "SessionFileRevisionMismatchError";
	}
}

function revisionFromStats(stats: BigIntStats): SessionFileRevision {
	return {
		dev: stats.dev,
		ino: stats.ino,
		size: stats.size,
		mtimeNs: stats.mtimeNs,
		ctimeNs: stats.ctimeNs,
	};
}

function revisionsEqual(left: SessionFileRevision, right: SessionFileRevision): boolean {
	return (
		left.dev === right.dev &&
		left.ino === right.ino &&
		left.size === right.size &&
		left.mtimeNs === right.mtimeNs &&
		left.ctimeNs === right.ctimeNs
	);
}

function assertRegularSessionStats(stats: BigIntStats, sessionFile: string): void {
	if (!stats.isFile()) throw new Error(`Session path is not a regular file: ${sessionFile}`);
}

function assertSessionFileCanBeReplaced(fd: number, sessionFile: string): void {
	const descriptorStats = fstatSync(fd, { bigint: true });
	const pathStats = lstatSync(sessionFile, { bigint: true });
	assertRegularSessionStats(descriptorStats, sessionFile);
	assertRegularSessionStats(pathStats, sessionFile);
	if (descriptorStats.dev !== pathStats.dev || descriptorStats.ino !== pathStats.ino) {
		throw new SessionFileRevisionMismatchError(sessionFile);
	}
	if (descriptorStats.nlink !== 1n || pathStats.nlink !== 1n) {
		throw new Error(`Session file has multiple hard links and cannot be safely replaced: ${sessionFile}`);
	}
}

/** Verify that an open descriptor and the canonical path still identify one unchanged file. */
function getStableSessionFileRevision(fd: number, sessionFile: string): SessionFileRevision {
	const descriptorStats = fstatSync(fd, { bigint: true });
	const pathStats = lstatSync(sessionFile, { bigint: true });
	assertRegularSessionStats(descriptorStats, sessionFile);
	assertRegularSessionStats(pathStats, sessionFile);
	if (descriptorStats.nlink !== 1n || pathStats.nlink !== 1n) {
		throw new Error(`Session file has multiple hard links and cannot be safely opened: ${sessionFile}`);
	}
	const descriptorRevision = revisionFromStats(descriptorStats);
	if (!revisionsEqual(descriptorRevision, revisionFromStats(pathStats))) {
		throw new SessionFileRevisionMismatchError(sessionFile);
	}
	return descriptorRevision;
}

function assertSessionFileRevision(fd: number, sessionFile: string, expectedRevision: SessionFileRevision): void {
	if (!revisionsEqual(getStableSessionFileRevision(fd, sessionFile), expectedRevision)) {
		throw new SessionFileRevisionMismatchError(sessionFile);
	}
}

function fsyncParentDirectory(filePath: string): void {
	if (process.platform === "win32") return;
	const directoryFd = openSync(dirname(filePath), "r");
	try {
		try {
			fsyncSync(directoryFd);
		} catch (error) {
			const code = typeof error === "object" && error !== null && "code" in error ? error.code : undefined;
			// Some filesystems and platforms explicitly do not support directory fsync.
			if (
				code !== "EINVAL" &&
				code !== "ENOTSUP" &&
				code !== "EOPNOTSUPP" &&
				code !== "ENOSYS" &&
				code !== "EBADF"
			) {
				throw error;
			}
		}
	} finally {
		closeSync(directoryFd);
	}
}

function withSessionFileLock<T>(sessionFile: string, operation: () => T): T {
	let release: (() => void) | undefined;
	const lockWaitArray = new Int32Array(new SharedArrayBuffer(4));
	for (let attempt = 0; attempt <= SESSION_FILE_LOCK_RETRY_ATTEMPTS; attempt++) {
		try {
			release = lockfile.lockSync(sessionFile, {
				stale: SESSION_FILE_LOCK_STALE_MS,
				update: SESSION_FILE_LOCK_STALE_MS / 2,
				retries: 0,
			});
			break;
		} catch (error) {
			const isLocked = typeof error === "object" && error !== null && "code" in error && error.code === "ELOCKED";
			if (!isLocked || attempt === SESSION_FILE_LOCK_RETRY_ATTEMPTS) throw error;
			const waitMs = Math.ceil(Math.min(100, 10 * 1.2 ** attempt) * (1 + Math.random()));
			Atomics.wait(lockWaitArray, 0, 0, waitMs);
		}
	}
	if (!release) throw new Error(`Failed to acquire session file lock: ${sessionFile}`);
	try {
		return operation();
	} finally {
		release();
	}
}

function appendLineAtRevision(
	sessionFile: string,
	expectedRevision: SessionFileRevision,
	line: Buffer | undefined,
): void {
	withSessionFileLock(sessionFile, () => {
		const fd = line ? openSync(sessionFile, constants.O_WRONLY | constants.O_APPEND) : openSync(sessionFile, "r");
		try {
			assertSessionFileRevision(fd, sessionFile, expectedRevision);
			if (line) {
				writeFileSync(fd, line);
				fsyncSync(fd);
			}
		} finally {
			closeSync(fd);
		}
	});
}

function prepareOrdinaryAppend(
	sessionFile: string,
	line: Buffer,
): {
	revision: SessionFileRevision;
	line: Buffer;
} {
	const fd = openSync(sessionFile, "r");
	try {
		const initialRevision = getStableSessionFileRevision(fd, sessionFile);
		if (initialRevision.size === 0n) throw new Error(`Session file is empty: ${sessionFile}`);
		if (initialRevision.size > BigInt(Number.MAX_SAFE_INTEGER)) {
			throw new Error(`Session file is too large to append safely: ${sessionFile}`);
		}
		const size = Number(initialRevision.size);
		const byte = Buffer.allocUnsafe(1);
		if (readSync(fd, byte, 0, 1, size - 1) !== 1) throw new SessionFileRevisionMismatchError(sessionFile);
		const terminated = byte[0] === 0x0a;
		let recordEnd = terminated ? size - 1 : size;

		// Ignore additional blank terminators and validate the latest physical record.
		while (recordEnd > 0) {
			if (readSync(fd, byte, 0, 1, recordEnd - 1) !== 1) {
				throw new SessionFileRevisionMismatchError(sessionFile);
			}
			if (byte[0] !== 0x0a) break;
			recordEnd--;
		}
		if (recordEnd === 0) throw new Error(`Session file has no final JSONL entry: ${sessionFile}`);

		let recordStart = 0;
		let searchEnd = recordEnd;
		const scanBuffer = Buffer.allocUnsafe(Math.min(64 * 1024, recordEnd));
		while (searchEnd > 0) {
			const chunkStart = Math.max(0, searchEnd - scanBuffer.length);
			const chunkLength = searchEnd - chunkStart;
			let chunkOffset = 0;
			while (chunkOffset < chunkLength) {
				const bytesRead = readSync(
					fd,
					scanBuffer,
					chunkOffset,
					chunkLength - chunkOffset,
					chunkStart + chunkOffset,
				);
				if (bytesRead === 0) throw new SessionFileRevisionMismatchError(sessionFile);
				chunkOffset += bytesRead;
			}
			const newlineIndex = scanBuffer.subarray(0, chunkLength).lastIndexOf(0x0a);
			if (newlineIndex !== -1) {
				recordStart = chunkStart + newlineIndex + 1;
				break;
			}
			searchEnd = chunkStart;
		}
		const record = Buffer.allocUnsafe(recordEnd - recordStart);
		let recordOffset = 0;
		while (recordOffset < record.length) {
			const bytesRead = readSync(fd, record, recordOffset, record.length - recordOffset, recordStart + recordOffset);
			if (bytesRead === 0) throw new SessionFileRevisionMismatchError(sessionFile);
			recordOffset += bytesRead;
		}
		try {
			const parsed = JSON.parse(record.toString("utf8")) as unknown;
			if (typeof parsed !== "object" || parsed === null) throw new Error("not an object");
		} catch {
			throw new Error(`Session file has a malformed final JSONL entry: ${sessionFile}`);
		}
		if (!revisionsEqual(getStableSessionFileRevision(fd, sessionFile), initialRevision)) {
			throw new SessionFileRevisionMismatchError(sessionFile);
		}
		return {
			revision: initialRevision,
			line: terminated ? line : Buffer.concat([Buffer.from("\n"), line]),
		};
	} finally {
		closeSync(fd);
	}
}

function appendLineWithRevisionRetry(sessionFile: string, line: Buffer): void {
	for (let attempt = 0; attempt <= SESSION_REVISION_RETRY_ATTEMPTS; attempt++) {
		try {
			const prepared = prepareOrdinaryAppend(sessionFile, line);
			appendLineAtRevision(sessionFile, prepared.revision, prepared.line);
			return;
		} catch (error) {
			if (!(error instanceof SessionFileRevisionMismatchError) || attempt === SESSION_REVISION_RETRY_ATTEMPTS) {
				throw error;
			}
		}
	}
}

/** Bound synchronous header discovery while allowing large cwd and custom metadata fields. */
const MAX_SESSION_HEADER_SCAN_BYTES = 1024 * 1024;

class SessionHeaderScanLimitError extends Error {
	constructor(filePath: string) {
		super(`Session header exceeds ${MAX_SESSION_HEADER_SCAN_BYTES}-byte scan limit: ${filePath}`);
		this.name = "SessionHeaderScanLimitError";
	}
}

function parseSessionEntryLine(line: string): FileEntry | null {
	if (!line.trim()) return null;
	try {
		return JSON.parse(line) as FileEntry;
	} catch {
		// Skip malformed lines
		return null;
	}
}

/** Exported for testing */
export function loadEntriesFromFile(filePath: string): FileEntry[] {
	const resolvedFilePath = normalizePath(filePath);
	if (!existsSync(resolvedFilePath)) return [];

	const entries: FileEntry[] = [];
	const fd = openSync(resolvedFilePath, "r");
	try {
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_READ_BUFFER_SIZE);
		let pending = "";

		while (true) {
			const bytesRead = readSync(fd, buffer, 0, buffer.length, null);
			if (bytesRead === 0) break;

			pending += decoder.write(buffer.subarray(0, bytesRead));
			let lineStart = 0;
			let newlineIndex = pending.indexOf("\n", lineStart);
			while (newlineIndex !== -1) {
				const entry = parseSessionEntryLine(pending.slice(lineStart, newlineIndex));
				if (entry) entries.push(entry);
				lineStart = newlineIndex + 1;
				newlineIndex = pending.indexOf("\n", lineStart);
			}
			pending = pending.slice(lineStart);
		}

		pending += decoder.end();
		const finalEntry = parseSessionEntryLine(pending);
		if (finalEntry) entries.push(finalEntry);
	} finally {
		closeSync(fd);
	}

	// Validate session header
	if (entries.length === 0) return entries;
	const header = entries[0];
	if (header.type !== "session" || typeof (header as { id?: unknown }).id !== "string") {
		return [];
	}

	return entries;
}

interface SessionFileSnapshot {
	entries: FileEntry[];
	revision: SessionFileRevision;
}

function loadStableSessionFile(filePath: string): SessionFileSnapshot {
	const fd = openSync(filePath, "r");
	try {
		const initialRevision = getStableSessionFileRevision(fd, filePath);
		if (initialRevision.size > BigInt(Number.MAX_SAFE_INTEGER)) {
			throw new Error(`Session file is too large to load safely: ${filePath}`);
		}
		const initialSize = Number(initialRevision.size);
		const entries: FileEntry[] = [];
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_READ_BUFFER_SIZE);
		let pending = "";
		let offset = 0;

		while (offset < initialSize) {
			const readLength = Math.min(buffer.length, initialSize - offset);
			const bytesRead = readSync(fd, buffer, 0, readLength, offset);
			if (bytesRead === 0) throw new SessionFileRevisionMismatchError(filePath);
			offset += bytesRead;
			pending += decoder.write(buffer.subarray(0, bytesRead));
			let newlineIndex = pending.indexOf("\n");
			while (newlineIndex !== -1) {
				const entry = parseSessionEntryLine(pending.slice(0, newlineIndex));
				if (entry) entries.push(entry);
				pending = pending.slice(newlineIndex + 1);
				newlineIndex = pending.indexOf("\n");
			}
		}
		pending += decoder.end();
		const finalEntry = parseSessionEntryLine(pending);
		if (finalEntry) entries.push(finalEntry);
		if (!revisionsEqual(getStableSessionFileRevision(fd, filePath), initialRevision)) {
			throw new SessionFileRevisionMismatchError(filePath);
		}
		if (
			entries.length > 0 &&
			(entries[0].type !== "session" || typeof (entries[0] as { id?: unknown }).id !== "string")
		) {
			return { entries: [], revision: initialRevision };
		}
		return { entries, revision: initialRevision };
	} finally {
		closeSync(fd);
	}
}

interface SessionNameTransactionScan {
	header: SessionHeader;
	latestSessionInfo: SessionInfoEntry | undefined;
	occupiedIds: Set<string>;
	revision: SessionFileRevision;
}

/** Strict streaming name scan performed before the short commit lock. */
function scanSessionForNameTransaction(filePath: string): SessionNameTransactionScan {
	const fd = openSync(filePath, "r");
	try {
		const initialRevision = getStableSessionFileRevision(fd, filePath);
		if (initialRevision.size === 0n) {
			throw new Error(`Session file is empty: ${filePath}`);
		}
		if (initialRevision.size > BigInt(Number.MAX_SAFE_INTEGER)) {
			throw new Error(`Session file is too large to scan safely: ${filePath}`);
		}
		const initialSize = Number(initialRevision.size);
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_READ_BUFFER_SIZE);
		const occupiedIds = new Set<string>();
		let header: SessionHeader | undefined;
		let latestSessionInfo: SessionInfoEntry | undefined;
		let pending = "";
		let offset = 0;

		const processLine = (line: string): void => {
			if (!line.trim()) return;
			let parsed: unknown;
			try {
				parsed = JSON.parse(line);
			} catch {
				throw new Error(`Session file has a malformed JSONL entry: ${filePath}`);
			}
			if (typeof parsed !== "object" || parsed === null || !("type" in parsed)) {
				throw new Error(`Session file has a non-object JSONL entry: ${filePath}`);
			}
			const entry = parsed as FileEntry;
			if (!header) {
				if (entry.type !== "session" || typeof (entry as { id?: unknown }).id !== "string") {
					throw new Error(`Session file is not a valid pi session: ${filePath}`);
				}
				header = entry;
				return;
			}
			if (entry.type === "session") {
				throw new Error(`Session file has multiple headers: ${filePath}`);
			}
			if (typeof (entry as { id?: unknown }).id !== "string") {
				throw new Error(`Session file entry has no valid ID: ${filePath}`);
			}
			occupiedIds.add(entry.id);
			if (entry.type === "session_info") latestSessionInfo = entry;
		};

		while (offset < initialSize) {
			const readLength = Math.min(buffer.length, initialSize - offset);
			const bytesRead = readSync(fd, buffer, 0, readLength, offset);
			if (bytesRead === 0) throw new SessionFileRevisionMismatchError(filePath);
			offset += bytesRead;
			pending += decoder.write(buffer.subarray(0, bytesRead));
			let newlineIndex = pending.indexOf("\n");
			while (newlineIndex !== -1) {
				processLine(pending.slice(0, newlineIndex));
				pending = pending.slice(newlineIndex + 1);
				newlineIndex = pending.indexOf("\n");
			}
		}
		pending += decoder.end();
		if (!revisionsEqual(getStableSessionFileRevision(fd, filePath), initialRevision)) {
			throw new SessionFileRevisionMismatchError(filePath);
		}
		if (pending.length > 0) {
			throw new Error(`Session file has an unterminated JSONL tail: ${filePath}`);
		}
		if (!header) {
			throw new Error(`Session file is not a valid pi session: ${filePath}`);
		}
		return { header, latestSessionInfo, occupiedIds, revision: initialRevision };
	} finally {
		closeSync(fd);
	}
}

/**
 * Inspect a physical line while searching for the first parsed session entry.
 * Blank and malformed lines are skipped to match loadEntriesFromFile().
 * Returns undefined to keep scanning, null for a parsed non-header entry, or the header.
 */
function parseSessionHeaderCandidate(line: string): SessionHeader | null | undefined {
	if (!line.trim()) return undefined;
	const entry = parseSessionEntryLine(line);
	if (!entry) return undefined;
	if (entry.type !== "session" || typeof (entry as { id?: unknown }).id !== "string") return null;
	return entry;
}

function readSessionHeader(filePath: string): SessionHeader | null {
	const fd = openSync(filePath, "r");
	try {
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_HEADER_READ_BUFFER_SIZE);
		const lineChunks: string[] = [];
		let scannedBytes = 0;

		while (scannedBytes < MAX_SESSION_HEADER_SCAN_BYTES) {
			const readLength = Math.min(buffer.length, MAX_SESSION_HEADER_SCAN_BYTES - scannedBytes);
			const bytesRead = readSync(fd, buffer, 0, readLength, null);
			if (bytesRead === 0) {
				lineChunks.push(decoder.end());
				return parseSessionHeaderCandidate(lineChunks.join("")) ?? null;
			}
			scannedBytes += bytesRead;

			const chunk = decoder.write(buffer.subarray(0, bytesRead));
			let lineStart = 0;
			let newlineIndex = chunk.indexOf("\n", lineStart);
			while (newlineIndex !== -1) {
				lineChunks.push(chunk.slice(lineStart, newlineIndex));
				const header = parseSessionHeaderCandidate(lineChunks.join(""));
				if (header !== undefined) return header;
				lineChunks.length = 0;
				lineStart = newlineIndex + 1;
				newlineIndex = chunk.indexOf("\n", lineStart);
			}
			lineChunks.push(chunk.slice(lineStart));
		}

		// Probe for EOF so a final header without a newline is allowed when it ends
		// exactly at the scan limit. Any additional byte exceeds the bounded scan.
		const probe = Buffer.allocUnsafe(1);
		if (readSync(fd, probe, 0, probe.length, null) === 0) {
			lineChunks.push(decoder.end());
			return parseSessionHeaderCandidate(lineChunks.join("")) ?? null;
		}
		throw new SessionHeaderScanLimitError(filePath);
	} finally {
		closeSync(fd);
	}
}

function readSessionHeaderForDiscovery(filePath: string): SessionHeader | null {
	try {
		return readSessionHeader(filePath);
	} catch {
		// Discovery is best-effort: unreadable or oversized files are not sessions,
		// and one corrupt file must not prevent other sessions from being found.
		return null;
	}
}

function getSessionHeaderCwd(header: SessionHeader): string | undefined {
	const cwd = (header as { cwd?: unknown }).cwd;
	return typeof cwd === "string" ? cwd : undefined;
}

function sessionCwdMatches(cwd: string | undefined, resolvedCwd: string): boolean {
	return cwd !== undefined && cwd !== "" && resolvePath(cwd) === resolvedCwd;
}

/** Exported for testing */
export function findMostRecentSession(sessionDir: string, cwd?: string): string | null {
	const resolvedSessionDir = normalizePath(sessionDir);
	const resolvedCwd = cwd ? resolvePath(cwd) : undefined;
	try {
		const files = readdirSync(resolvedSessionDir)
			.filter((f) => f.endsWith(".jsonl"))
			.map((f) => join(resolvedSessionDir, f))
			.map((path) => ({ path, header: readSessionHeaderForDiscovery(path) }))
			.filter(
				(file): file is { path: string; header: SessionHeader } =>
					file.header !== null &&
					(!resolvedCwd || sessionCwdMatches(getSessionHeaderCwd(file.header), resolvedCwd)),
			)
			.map(({ path }) => ({ path, mtime: statSync(path).mtime }))
			.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

		return files[0]?.path || null;
	} catch {
		// Directory access and stat races make recent-session discovery unavailable.
		return null;
	}
}

function isMessageWithContent(message: AgentMessage): message is Message {
	return typeof (message as Message).role === "string" && "content" in message;
}

function extractTextContent(message: Message): string {
	const content = message.content;
	if (typeof content === "string") {
		return content;
	}
	return content
		.filter((block): block is TextContent => block.type === "text")
		.map((block) => block.text)
		.join(" ");
}

function getMessageActivityTime(entry: SessionMessageEntry): number | undefined {
	const message = entry.message;
	if (!isMessageWithContent(message)) return undefined;
	if (message.role !== "user" && message.role !== "assistant") return undefined;

	const msgTimestamp = (message as { timestamp?: number }).timestamp;
	if (typeof msgTimestamp === "number") {
		return msgTimestamp;
	}

	const t = new Date(entry.timestamp).getTime();
	return Number.isNaN(t) ? undefined : t;
}

async function buildSessionInfo(filePath: string): Promise<SessionInfo | null> {
	try {
		const stats = await stat(filePath);
		let header: SessionHeader | null = null;
		let messageCount = 0;
		let firstMessage = "";
		const allMessages: string[] = [];
		let name: string | undefined;
		let lastActivityTime: number | undefined;

		const rl = createInterface({
			input: createReadStream(filePath, { encoding: "utf8" }),
			crlfDelay: Infinity,
		});

		for await (const line of rl) {
			const entry = parseSessionEntryLine(line);
			if (!entry) continue;

			if (!header) {
				if (entry.type !== "session") return null;
				header = entry;
				continue;
			}

			// Extract session name (use latest, including explicit clears)
			if (entry.type === "session_info") {
				name = entry.name?.trim() || undefined;
			}

			if (entry.type !== "message") continue;
			messageCount++;

			const activityTime = getMessageActivityTime(entry);
			if (typeof activityTime === "number") {
				lastActivityTime = Math.max(lastActivityTime ?? 0, activityTime);
			}

			const message = entry.message;
			if (!isMessageWithContent(message)) continue;
			if (message.role !== "user" && message.role !== "assistant") continue;

			const textContent = extractTextContent(message);
			if (!textContent) continue;

			allMessages.push(textContent);
			if (!firstMessage && message.role === "user") {
				firstMessage = textContent;
			}
		}

		if (!header) return null;

		const cwd = typeof header.cwd === "string" ? header.cwd : "";
		const parentSessionPath = header.parentSession;
		const headerTime = typeof header.timestamp === "string" ? new Date(header.timestamp).getTime() : NaN;
		const modified =
			typeof lastActivityTime === "number" && lastActivityTime > 0
				? new Date(lastActivityTime)
				: !Number.isNaN(headerTime)
					? new Date(headerTime)
					: stats.mtime;

		return {
			path: filePath,
			id: header.id,
			cwd,
			name,
			parentSessionPath,
			created: new Date(header.timestamp),
			modified,
			messageCount,
			firstMessage: firstMessage || "(no messages)",
			allMessagesText: allMessages.join(" "),
		};
	} catch {
		return null;
	}
}

export type SessionListProgress = (loaded: number, total: number) => void;

const MAX_CONCURRENT_SESSION_INFO_LOADS = 10;

async function buildSessionInfosWithConcurrency(
	files: string[],
	onLoaded: () => void,
): Promise<(SessionInfo | null)[]> {
	const results: (SessionInfo | null)[] = new Array(files.length).fill(null);
	const inFlight = new Set<Promise<void>>();
	let nextIndex = 0;

	const startNext = (): void => {
		const index = nextIndex++;
		const file = files[index];
		if (!file) return;

		let task: Promise<void>;
		task = buildSessionInfo(file)
			.then((info) => {
				results[index] = info;
			})
			.catch(() => {
				results[index] = null;
			})
			.finally(() => {
				inFlight.delete(task);
				onLoaded();
			});
		inFlight.add(task);
	};

	while (nextIndex < files.length || inFlight.size > 0) {
		while (nextIndex < files.length && inFlight.size < MAX_CONCURRENT_SESSION_INFO_LOADS) {
			startNext();
		}
		if (inFlight.size > 0) {
			await Promise.race(inFlight);
		}
	}

	return results;
}

async function listSessionsFromDir(
	dir: string,
	onProgress?: SessionListProgress,
	progressOffset = 0,
	progressTotal?: number,
): Promise<SessionInfo[]> {
	const sessions: SessionInfo[] = [];
	if (!existsSync(dir)) {
		return sessions;
	}

	try {
		const dirEntries = await readdir(dir);
		const files = dirEntries.filter((f) => f.endsWith(".jsonl")).map((f) => join(dir, f));
		const total = progressTotal ?? files.length;

		let loaded = 0;
		const results = await buildSessionInfosWithConcurrency(files, () => {
			loaded++;
			onProgress?.(progressOffset + loaded, total);
		});
		for (const info of results) {
			if (info) {
				sessions.push(info);
			}
		}
	} catch {
		// Return empty list on error
	}

	return sessions;
}

function sessionFileMatchesEntries(filePath: string, entries: readonly FileEntry[]): boolean {
	let fd: number | undefined;
	try {
		fd = openSync(filePath, "r");
		const descriptorStats = fstatSync(fd, { bigint: true });
		const pathStats = lstatSync(filePath, { bigint: true });
		assertRegularSessionStats(descriptorStats, filePath);
		assertRegularSessionStats(pathStats, filePath);
		const revision = revisionFromStats(descriptorStats);
		if (!revisionsEqual(revision, revisionFromStats(pathStats))) return false;
		let fileOffset = 0;
		for (const entry of entries) {
			const expected = Buffer.from(`${JSON.stringify(entry)}\n`);
			const actual = Buffer.allocUnsafe(expected.length);
			let lineOffset = 0;
			while (lineOffset < actual.length) {
				const bytesRead = readSync(fd, actual, lineOffset, actual.length - lineOffset, fileOffset + lineOffset);
				if (bytesRead === 0) return false;
				lineOffset += bytesRead;
			}
			if (!actual.equals(expected)) return false;
			fileOffset += actual.length;
		}
		if (BigInt(fileOffset) !== revision.size) return false;
		const finalDescriptorStats = fstatSync(fd, { bigint: true });
		const finalPathStats = lstatSync(filePath, { bigint: true });
		return (
			revisionsEqual(revisionFromStats(finalDescriptorStats), revision) &&
			revisionsEqual(revisionFromStats(finalPathStats), revision)
		);
	} catch {
		return false;
	} finally {
		if (fd !== undefined) closeSync(fd);
	}
}

function sessionFileHasEntriesPrefixAndCompleteTail(
	filePath: string,
	entries: readonly FileEntry[],
	expectedIdentity: Pick<SessionFileRevision, "dev" | "ino">,
): boolean {
	let fd: number | undefined;
	try {
		fd = openSync(filePath, "r");
		const descriptorStats = fstatSync(fd, { bigint: true });
		const pathStats = lstatSync(filePath, { bigint: true });
		assertRegularSessionStats(descriptorStats, filePath);
		assertRegularSessionStats(pathStats, filePath);
		const revision = revisionFromStats(descriptorStats);
		if (
			revision.dev !== expectedIdentity.dev ||
			revision.ino !== expectedIdentity.ino ||
			!revisionsEqual(revision, revisionFromStats(pathStats)) ||
			revision.size > BigInt(Number.MAX_SAFE_INTEGER)
		) {
			return false;
		}
		const expectedPrefix = Buffer.from(entries.map((entry) => `${JSON.stringify(entry)}\n`).join(""));
		if (revision.size < BigInt(expectedPrefix.length)) return false;
		const content = Buffer.allocUnsafe(Number(revision.size));
		let offset = 0;
		while (offset < content.length) {
			const bytesRead = readSync(fd, content, offset, content.length - offset, offset);
			if (bytesRead === 0) return false;
			offset += bytesRead;
		}
		if (!content.subarray(0, expectedPrefix.length).equals(expectedPrefix)) return false;
		const tail = content.subarray(expectedPrefix.length);
		if (tail.length > 0) {
			if (tail[tail.length - 1] !== 0x0a) return false;
			for (const line of tail.toString("utf8").split("\n")) {
				if (!line) continue;
				const parsed = JSON.parse(line) as unknown;
				if (typeof parsed !== "object" || parsed === null) return false;
			}
		}
		const finalDescriptorStats = fstatSync(fd, { bigint: true });
		const finalPathStats = lstatSync(filePath, { bigint: true });
		return (
			revisionsEqual(revisionFromStats(finalDescriptorStats), revision) &&
			revisionsEqual(revisionFromStats(finalPathStats), revision)
		);
	} catch {
		return false;
	} finally {
		if (fd !== undefined) closeSync(fd);
	}
}

function getSamePhysicalMaterializeAliases(destination: string): string[] {
	const destinationStats = lstatSync(destination, { bigint: true });
	assertRegularSessionStats(destinationStats, destination);
	const prefix = `${basename(destination)}.materialize-`;
	const aliases: string[] = [];
	for (const name of readdirSync(dirname(destination))) {
		if (!name.startsWith(prefix)) continue;
		const candidate = join(dirname(destination), name);
		try {
			const candidateStats = lstatSync(candidate, { bigint: true });
			if (
				candidateStats.isFile() &&
				candidateStats.dev === destinationStats.dev &&
				candidateStats.ino === destinationStats.ino
			) {
				aliases.push(candidate);
			}
		} catch (error) {
			if (!(typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT")) {
				throw error;
			}
		}
	}
	return aliases;
}

function cleanupMaterializeAliases(destination: string): number {
	const aliases = getSamePhysicalMaterializeAliases(destination);
	for (const alias of aliases) unlinkSync(alias);
	return aliases.length;
}

function reconcileMaterializeAliasesBeforeOpen(destination: string): void {
	const aliases = getSamePhysicalMaterializeAliases(destination);
	if (aliases.length === 0) return;
	for (const alias of aliases) unlinkSync(alias);
	try {
		fsyncParentDirectory(destination);
	} catch {
		// The destination was already committed; stable validation follows below.
	}
}

/**
 * Manages conversation sessions as append-only trees stored in JSONL files.
 *
 * Each session entry has an id and parentId forming a tree structure. The "leaf"
 * pointer tracks the current position. Appending creates a child of the current leaf.
 * Branching moves the leaf to an earlier entry, allowing new branches without
 * modifying history.
 *
 * Use buildSessionContext() to get the resolved message list for the LLM, which
 * handles compaction summaries and follows the path from root to current leaf.
 */
export class SessionManager {
	private sessionId: string = "";
	private sessionFile: string | undefined;
	private sessionDir: string;
	private cwd: string;
	private persist: boolean;
	private flushed: boolean = false;
	private fileEntries: FileEntry[] = [];
	private byId: Map<string, SessionEntry> = new Map();
	private labelsById: Map<string, string> = new Map();
	private labelTimestampsById: Map<string, string> = new Map();
	private leafId: string | null = null;

	private constructor(
		cwd: string,
		sessionDir: string,
		sessionFile: string | undefined,
		persist: boolean,
		newSessionOptions?: NewSessionOptions,
	) {
		this.cwd = resolvePath(cwd);
		this.sessionDir = normalizePath(sessionDir);
		this.persist = persist;
		if (persist && this.sessionDir) {
			if (!existsSync(this.sessionDir)) mkdirSync(this.sessionDir, { recursive: true });
			this.sessionDir = canonicalizePath(this.sessionDir);
		}

		if (sessionFile) {
			this._setSessionFile(sessionFile);
		} else {
			this.newSession(newSessionOptions);
		}
	}

	/** Switch to a different session file (used for resume and branching) */
	setSessionFile(sessionFile: string): void {
		this._setSessionFile(sessionFile);
	}

	private _setSessionFile(sessionFile: string): void {
		const previous = {
			sessionFile: this.sessionFile,
			sessionId: this.sessionId,
			fileEntries: [...this.fileEntries],
			byId: new Map(this.byId),
			labelsById: new Map(this.labelsById),
			labelTimestampsById: new Map(this.labelTimestampsById),
			leafId: this.leafId,
			flushed: this.flushed,
		};
		try {
			// Bind aliases to one canonical path. Existing files are then loaded through
			// a stable descriptor/path snapshot before any short commit lock is acquired.
			this.sessionFile = resolveSessionFileIdentity(sessionFile);
			if (existsSync(this.sessionFile)) {
				reconcileMaterializeAliasesBeforeOpen(this.sessionFile);
				const explicitPath = this.sessionFile;
				let loadedEntries: FileEntry[] | undefined;
				for (let attempt = 0; attempt <= SESSION_REVISION_RETRY_ATTEMPTS; attempt++) {
					try {
						const snapshot = loadStableSessionFile(explicitPath);
						let entries = snapshot.entries;
						if (entries.length === 0) {
							if (snapshot.revision.size > 0n) {
								throw new Error(`Session file is not a valid pi session: ${explicitPath}`);
							}
							entries = [
								{
									type: "session",
									version: CURRENT_SESSION_VERSION,
									id: createSessionId(),
									timestamp: new Date().toISOString(),
									cwd: this.cwd,
								},
							];
							this._rewriteFile(snapshot.revision, entries);
						} else if (migrateToCurrentVersion(entries)) {
							this._rewriteFile(snapshot.revision, entries);
						}
						loadedEntries = entries;
						break;
					} catch (error) {
						if (
							!(error instanceof SessionFileRevisionMismatchError) ||
							attempt === SESSION_REVISION_RETRY_ATTEMPTS
						) {
							throw error;
						}
					}
				}
				if (!loadedEntries) throw new Error(`Failed to load stable session file: ${explicitPath}`);
				const header = loadedEntries.find((entry) => entry.type === "session") as SessionHeader | undefined;
				this.fileEntries = loadedEntries;
				this.sessionId = header?.id ?? createSessionId();
				this._buildIndex();
				this.flushed = true;
			} else {
				const explicitPath = this.sessionFile;
				this.newSession();
				this.sessionFile = explicitPath; // preserve explicit path from --session flag
			}
		} catch (error) {
			this.sessionFile = previous.sessionFile;
			this.sessionId = previous.sessionId;
			this.fileEntries = previous.fileEntries;
			this.byId = previous.byId;
			this.labelsById = previous.labelsById;
			this.labelTimestampsById = previous.labelTimestampsById;
			this.leafId = previous.leafId;
			this.flushed = previous.flushed;
			throw error;
		}
	}

	newSession(options?: NewSessionOptions): string | undefined {
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		this.sessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: this.sessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: options?.parentSession,
		};
		this.fileEntries = [header];
		this.byId.clear();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		this.flushed = false;

		if (this.persist) {
			const fileTimestamp = timestamp.replace(/[:.]/g, "-");
			this.sessionFile = join(this.getSessionDir(), `${fileTimestamp}_${this.sessionId}.jsonl`);
		}
		return this.sessionFile;
	}

	private _buildIndex(): void {
		this.byId.clear();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		for (const entry of this.fileEntries) {
			if (entry.type === "session") continue;
			this.byId.set(entry.id, entry);
			// session_info is side metadata. Legacy descendants can still point to it,
			// but the metadata entry itself never becomes the conversation leaf.
			if (entry.type !== "session_info") {
				this.leafId = entry.id;
			}
			if (entry.type === "label") {
				if (entry.label) {
					this.labelsById.set(entry.targetId, entry.label);
					this.labelTimestampsById.set(entry.targetId, entry.timestamp);
				} else {
					this.labelsById.delete(entry.targetId);
					this.labelTimestampsById.delete(entry.targetId);
				}
			}
		}
	}

	private _rewriteFile(
		expectedRevision?: SessionFileRevision,
		entries: readonly FileEntry[] = this.fileEntries,
	): void {
		if (!this.persist || !this.sessionFile) return;
		const destination = this.sessionFile;
		const temporary = `${destination}.rewrite-${process.pid}-${randomUUID()}`;
		let fd: number | undefined;
		let replaced = false;
		try {
			// Serialize and fsync the replacement before acquiring the commit lock.
			fd = openSync(temporary, "wx", 0o600);
			for (const entry of entries) {
				writeFileSync(fd, `${JSON.stringify(entry)}\n`);
			}
			fsyncSync(fd);
			closeSync(fd);
			fd = undefined;

			const publish = (): void => {
				if (expectedRevision || existsSync(destination)) {
					const currentFd = openSync(destination, "r");
					try {
						if (expectedRevision) assertSessionFileRevision(currentFd, destination, expectedRevision);
						assertSessionFileCanBeReplaced(currentFd, destination);
					} finally {
						closeSync(currentFd);
					}
				}
				renameSync(temporary, destination);
				replaced = true;
				fsyncParentDirectory(destination);
			};
			if (expectedRevision) {
				withSessionFileLock(destination, publish);
			} else {
				publish();
			}
		} catch (error) {
			if (fd !== undefined) closeSync(fd);
			if (existsSync(temporary)) unlinkSync(temporary);
			// renameSync already committed the replacement. Keep manager state aligned
			// with that publication rather than reporting the whole transaction failed.
			if (replaced && sessionFileMatchesEntries(destination, entries)) return;
			throw error;
		}
	}

	/**
	 * Atomically publish a newly-created session before another component stores
	 * its proposed path as durable identity. Existing sessions are already
	 * materialized; an unexpected path collision fails closed.
	 */
	materialize(): void {
		if (!this.persist || !this.sessionFile || this.flushed) return;
		const destination = this.sessionFile;
		if (existsSync(destination)) {
			// Reconcile a prior link-before-unlink crash only when a generated temp
			// alias has the same physical identity and the destination has our content.
			if (sessionFileMatchesEntries(destination, this.fileEntries)) {
				const aliases = getSamePhysicalMaterializeAliases(destination);
				if (aliases.length > 0) {
					try {
						for (const alias of aliases) unlinkSync(alias);
						fsyncParentDirectory(destination);
					} catch {
						// The destination is already the authoritative committed publication.
					}
					this.flushed = true;
					return;
				}
			}
			throw new Error(`Session file already exists before materialization: ${destination}`);
		}
		const temporary = `${destination}.materialize-${process.pid}-${randomUUID()}`;
		let fd: number | undefined;
		let published = false;
		let publishedIdentity: Pick<SessionFileRevision, "dev" | "ino"> | undefined;
		try {
			fd = openSync(temporary, "wx", 0o600);
			for (const entry of this.fileEntries) {
				writeFileSync(fd, `${JSON.stringify(entry)}\n`);
			}
			fsyncSync(fd);
			const temporaryStats = fstatSync(fd, { bigint: true });
			publishedIdentity = { dev: temporaryStats.dev, ino: temporaryStats.ino };
			closeSync(fd);
			fd = undefined;
			// link is an atomic no-clobber publication on the same filesystem.
			linkSync(temporary, destination);
			published = true;
			unlinkSync(temporary);
			// Persist the final destination-only directory state before another
			// component may durably publish this session path.
			fsyncParentDirectory(destination);
			this.flushed = true;
		} catch (error) {
			if (fd !== undefined) closeSync(fd);
			if (!published) {
				if (existsSync(temporary)) unlinkSync(temporary);
				throw error;
			}
			// linkSync already committed the destination. Suppress the post-publication
			// error only when it is still that temp inode, our bytes are an exact prefix,
			// and every concurrently appended trailing record is complete JSONL.
			if (
				!publishedIdentity ||
				!sessionFileHasEntriesPrefixAndCompleteTail(destination, this.fileEntries, publishedIdentity)
			) {
				throw error;
			}
			try {
				cleanupMaterializeAliases(destination);
				fsyncParentDirectory(destination);
			} catch {
				// The verified destination remains the authoritative committed publication.
			}
			this.flushed = true;
		}
	}

	isPersisted(): boolean {
		return this.persist;
	}

	getCwd(): string {
		return this.cwd;
	}

	getSessionDir(): string {
		return this.sessionDir;
	}

	usesDefaultSessionDir(): boolean {
		return this.sessionDir === getDefaultSessionDirPath(this.cwd);
	}

	getSessionId(): string {
		return this.sessionId;
	}

	getSessionFile(): string | undefined {
		return this.sessionFile;
	}

	_persist(entry: SessionEntry): void {
		if (!this.persist || !this.sessionFile) return;

		const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message.role === "assistant");
		if (!hasAssistant) {
			if (this.flushed) {
				appendLineWithRevisionRetry(this.sessionFile, Buffer.from(`${JSON.stringify(entry)}\n`));
			} else {
				// Mark as not flushed so when assistant arrives, all entries get written
				this.flushed = false;
			}
			return;
		}

		if (!this.flushed) {
			this.materialize();
		} else {
			appendLineWithRevisionRetry(this.sessionFile, Buffer.from(`${JSON.stringify(entry)}\n`));
		}
	}

	private _appendEntry(entry: SessionEntry): void {
		const previousLeafId = this.leafId;
		const previousFlushed = this.flushed;
		this.fileEntries.push(entry);
		this.byId.set(entry.id, entry);
		this.leafId = entry.id;
		try {
			this._persist(entry);
		} catch (error) {
			this.fileEntries.pop();
			this.byId.delete(entry.id);
			this.leafId = previousLeafId;
			this.flushed = previousFlushed;
			throw error;
		}
	}

	/** Append a message as child of current leaf, then advance leaf. Returns entry id.
	 * Does not allow writing CompactionSummaryMessage and BranchSummaryMessage directly.
	 * Reason: we want these to be top-level entries in the session, not message session entries,
	 * so it is easier to find them.
	 * These need to be appended via appendCompaction() and appendBranchSummary() methods.
	 */
	appendMessage(message: Message | CustomMessage | BashExecutionMessage): string {
		const entry: SessionMessageEntry = {
			type: "message",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			message,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a thinking level change as child of current leaf, then advance leaf. Returns entry id. */
	appendThinkingLevelChange(thinkingLevel: string): string {
		const entry: ThinkingLevelChangeEntry = {
			type: "thinking_level_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			thinkingLevel,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a model change as child of current leaf, then advance leaf. Returns entry id. */
	appendModelChange(provider: string, modelId: string): string {
		const entry: ModelChangeEntry = {
			type: "model_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			provider,
			modelId,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a compaction summary as child of current leaf, then advance leaf. Returns entry id. */
	appendCompaction<T = unknown>(
		summary: string,
		firstKeptEntryId: string,
		tokensBefore: number,
		details?: T,
		fromHook?: boolean,
		usage?: Usage,
	): string {
		const entry: CompactionEntry<T> = {
			type: "compaction",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			summary,
			firstKeptEntryId,
			tokensBefore,
			details,
			usage,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a custom entry (for extensions) as child of current leaf, then advance leaf. Returns entry id. */
	appendCustomEntry(customType: string, data?: unknown): string {
		const entry: CustomEntry = {
			type: "custom",
			customType,
			data,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	private _assertCanRefreshSessionNameMetadata(entry: SessionInfoEntry | undefined): void {
		if (!entry) return;
		const existing = this.byId.get(entry.id);
		if (
			existing &&
			(existing.type !== "session_info" ||
				existing.name !== entry.name ||
				existing.origin !== entry.origin ||
				existing.parentId !== entry.parentId)
		) {
			throw new Error(`Conflicting session entry ID during name refresh: ${entry.id}`);
		}
	}

	private _refreshSessionNameMetadata(entry: SessionInfoEntry | undefined): void {
		this._assertCanRefreshSessionNameMetadata(entry);
		if (!entry || this.byId.has(entry.id)) return;
		this.fileEntries.push(entry);
		this.byId.set(entry.id, entry);
	}

	private _appendSessionInfo(
		name: string,
		options: SessionNameWriteOptions,
		expectedState?: SessionNameState,
	): SessionNameWriteResult {
		const sanitizedName = name.replace(/[\r\n]+/g, " ").trim();
		const appendToCurrentState = (): SessionNameWriteResult => {
			const currentState = this.getSessionNameState();
			if (
				expectedState &&
				(currentState.entryId !== expectedState.entryId || currentState.name !== expectedState.name)
			) {
				return { written: false, currentState };
			}
			const entry: SessionInfoEntry = {
				type: "session_info",
				id: generateId(this.byId),
				parentId: this.leafId,
				timestamp: new Date().toISOString(),
				name: sanitizedName,
				...(options.origin ? { origin: options.origin } : {}),
			};
			this.fileEntries.push(entry);
			this.byId.set(entry.id, entry);
			const previousFlushed = this.flushed;
			try {
				this._persist(entry);
			} catch (error) {
				this.fileEntries.pop();
				this.byId.delete(entry.id);
				this.flushed = previousFlushed;
				throw error;
			}
			return { written: true, entryId: entry.id };
		};

		if (!this.persist || !this.sessionFile || !existsSync(this.sessionFile)) {
			return appendToCurrentState();
		}

		const sessionFile = this.sessionFile;
		for (let attempt = 0; attempt <= SESSION_REVISION_RETRY_ATTEMPTS; attempt++) {
			try {
				const physical = scanSessionForNameTransaction(sessionFile);
				if (physical.header.id !== this.sessionId) {
					throw new Error(`Session file changed during name transaction: ${this.sessionFile}`);
				}

				// The outside-lock scan is authoritative only after the short commit lock
				// verifies its exact physical revision. Never replace live conversation state.
				const physicalNameEntry = physical.latestSessionInfo;
				this._assertCanRefreshSessionNameMetadata(physicalNameEntry);
				const currentState: SessionNameState = physicalNameEntry
					? { name: physicalNameEntry.name?.trim() || undefined, entryId: physicalNameEntry.id }
					: { name: undefined, entryId: undefined };
				const matchesExpected =
					!expectedState ||
					(currentState.entryId === expectedState.entryId && currentState.name === expectedState.name);
				let entry: SessionInfoEntry | undefined;
				if (matchesExpected) {
					const occupiedIds = new Set([...this.byId.keys(), ...physical.occupiedIds]);
					entry = {
						type: "session_info",
						id: generateId(occupiedIds),
						parentId: this.leafId,
						timestamp: new Date().toISOString(),
						name: sanitizedName,
						...(options.origin ? { origin: options.origin } : {}),
					};
				}
				appendLineAtRevision(
					sessionFile,
					physical.revision,
					entry ? Buffer.from(`${JSON.stringify(entry)}\n`) : undefined,
				);

				this._refreshSessionNameMetadata(physicalNameEntry);
				if (!entry) return { written: false, currentState };
				this.fileEntries.push(entry);
				this.byId.set(entry.id, entry);
				return { written: true, entryId: entry.id };
			} catch (error) {
				if (!(error instanceof SessionFileRevisionMismatchError) || attempt === SESSION_REVISION_RETRY_ATTEMPTS) {
					throw error;
				}
			}
		}
		throw new Error(`Failed to commit stable session name transaction: ${sessionFile}`);
	}

	/**
	 * Append a session name unconditionally. File-backed writers coordinate through
	 * one lock so a later human write remains canonical. Origin defaults to human.
	 * Returns the new entry id.
	 */
	appendSessionInfo(name: string, options: SessionNameWriteOptions = {}): string {
		const result = this._appendSessionInfo(name, { origin: options.origin ?? "human" });
		if (!result.written) {
			throw new Error("Unconditional session name write was not written");
		}
		return result.entryId;
	}

	/** Append a session name only when the latest physical name revision exactly matches. */
	appendSessionInfoIfCurrent(
		name: string,
		expectedState: SessionNameState,
		options: SessionNameWriteOptions = {},
	): SessionNameWriteResult {
		return this._appendSessionInfo(name, options, expectedState);
	}

	/** Get the latest name and its exact session_info revision, including explicit clears. */
	getSessionNameState(): SessionNameState {
		const entry = getLatestSessionInfoEntry(this.fileEntries);
		return entry
			? { name: entry.name?.trim() || undefined, entryId: entry.id }
			: { name: undefined, entryId: undefined };
	}

	/** Get the current session name from the latest session_info entry, if any. */
	getSessionName(): string | undefined {
		return this.getSessionNameState().name;
	}

	/**
	 * Append a custom message entry (for extensions) that participates in LLM context.
	 * @param customType Extension identifier for filtering on reload
	 * @param content Message content (string or TextContent/ImageContent array)
	 * @param display Whether to show in TUI (true = styled display, false = hidden)
	 * @param details Optional extension-specific metadata (not sent to LLM)
	 * @returns Entry id
	 */
	appendCustomMessageEntry<T = unknown>(
		customType: string,
		content: string | (TextContent | ImageContent)[],
		display: boolean,
		details?: T,
	): string {
		const entry: CustomMessageEntry<T> = {
			type: "custom_message",
			customType,
			content,
			display,
			details,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	// =========================================================================
	// Tree Traversal
	// =========================================================================

	getLeafId(): string | null {
		return this.leafId;
	}

	getLeafEntry(): SessionEntry | undefined {
		return this.leafId ? this.byId.get(this.leafId) : undefined;
	}

	getEntry(id: string): SessionEntry | undefined {
		return this.byId.get(id);
	}

	/**
	 * Get all direct children of an entry.
	 */
	getChildren(parentId: string): SessionEntry[] {
		const children: SessionEntry[] = [];
		for (const entry of this.byId.values()) {
			if (entry.parentId === parentId) {
				children.push(entry);
			}
		}
		return children;
	}

	/**
	 * Get the label for an entry, if any.
	 */
	getLabel(id: string): string | undefined {
		return this.labelsById.get(id);
	}

	/**
	 * Set or clear a label on an entry.
	 * Labels are user-defined markers for bookmarking/navigation.
	 * Pass undefined or empty string to clear the label.
	 */
	appendLabelChange(targetId: string, label: string | undefined): string {
		if (!this.byId.has(targetId)) {
			throw new Error(`Entry ${targetId} not found`);
		}
		const entry: LabelEntry = {
			type: "label",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			targetId,
			label,
		};
		this._appendEntry(entry);
		if (label) {
			this.labelsById.set(targetId, label);
			this.labelTimestampsById.set(targetId, entry.timestamp);
		} else {
			this.labelsById.delete(targetId);
			this.labelTimestampsById.delete(targetId);
		}
		return entry.id;
	}

	/**
	 * Walk from entry to root, returning all entries in path order.
	 * Includes all entry types (messages, compaction, model changes, etc.).
	 * Use buildSessionContext() to get the resolved messages for the LLM.
	 */
	getBranch(fromId?: string): SessionEntry[] {
		const path: SessionEntry[] = [];
		const startId = fromId ?? this.leafId;
		let current = startId ? this.byId.get(startId) : undefined;
		while (current) {
			path.push(current);
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		path.reverse();
		return path;
	}

	/**
	 * Build the active, compaction-aware entry list for context/rendering.
	 * Uses tree traversal from current leaf.
	 */
	buildContextEntries(): SessionEntry[] {
		return buildContextEntries(this.getEntries(), this.leafId, this.byId);
	}

	/**
	 * Build the session context (what gets sent to the LLM).
	 * Uses tree traversal from current leaf.
	 */
	buildSessionContext(): SessionContext {
		return buildSessionContext(this.getEntries(), this.leafId, this.byId);
	}

	/**
	 * Get session header.
	 */
	getHeader(): SessionHeader | null {
		const h = this.fileEntries.find((e) => e.type === "session");
		return h ? (h as SessionHeader) : null;
	}

	/**
	 * Get all session entries (excludes header). Returns a shallow copy.
	 * The session is append-only: use appendXXX() to add entries, branch() to
	 * change the leaf pointer. Entries cannot be modified or deleted.
	 */
	getEntries(): SessionEntry[] {
		return this.fileEntries.filter((e): e is SessionEntry => e.type !== "session");
	}

	/**
	 * Get the session as a tree structure. Returns a shallow defensive copy of all entries.
	 * A well-formed session has exactly one root (first entry with parentId === null).
	 * Orphaned entries (broken parent chain) are also returned as roots.
	 */
	getTree(): SessionTreeNode[] {
		const entries = this.getEntries();
		const nodeMap = new Map<string, SessionTreeNode>();
		const roots: SessionTreeNode[] = [];

		// Create nodes with resolved labels
		for (const entry of entries) {
			const label = this.labelsById.get(entry.id);
			const labelTimestamp = this.labelTimestampsById.get(entry.id);
			nodeMap.set(entry.id, { entry, children: [], label, labelTimestamp });
		}

		// Build tree
		for (const entry of entries) {
			const node = nodeMap.get(entry.id)!;
			if (entry.parentId === null || entry.parentId === entry.id) {
				roots.push(node);
			} else {
				const parent = nodeMap.get(entry.parentId);
				if (parent) {
					parent.children.push(node);
				} else {
					// Orphan - treat as root
					roots.push(node);
				}
			}
		}

		// Sort children by timestamp (oldest first, newest at bottom)
		// Use iterative approach to avoid stack overflow on deep trees
		const stack: SessionTreeNode[] = [...roots];
		while (stack.length > 0) {
			const node = stack.pop()!;
			node.children.sort((a, b) => new Date(a.entry.timestamp).getTime() - new Date(b.entry.timestamp).getTime());
			stack.push(...node.children);
		}

		return roots;
	}

	// =========================================================================
	// Branching
	// =========================================================================

	/**
	 * Start a new branch from an earlier conversation entry.
	 * Moves the leaf pointer to the specified entry. The next appendXXX() call
	 * will create a child of that entry, forming a new branch. Existing entries
	 * are not modified or deleted. Session metadata cannot be a branch target.
	 */
	branch(branchFromId: string): void {
		const branchFrom = this.byId.get(branchFromId);
		if (!branchFrom) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		if (branchFrom.type === "session_info") {
			throw new Error("Session metadata cannot be selected as a branch target");
		}
		this.leafId = branchFromId;
	}

	/**
	 * Reset the leaf pointer to null (before any entries).
	 * The next appendXXX() call will create a new root entry (parentId = null).
	 * Use this when navigating to re-edit the first user message.
	 */
	resetLeaf(): void {
		this.leafId = null;
	}

	/**
	 * Start a new branch with a summary of the abandoned path.
	 * Same as branch(), including rejection of session metadata targets, but also
	 * appends a branch_summary entry that captures context from the abandoned path.
	 */
	branchWithSummary(
		branchFromId: string | null,
		summary: string,
		details?: unknown,
		fromHook?: boolean,
		usage?: Usage,
	): string {
		if (branchFromId !== null) {
			const branchFrom = this.byId.get(branchFromId);
			if (!branchFrom) {
				throw new Error(`Entry ${branchFromId} not found`);
			}
			if (branchFrom.type === "session_info") {
				throw new Error("Session metadata cannot be selected as a branch target");
			}
		}
		const previousLeafId = this.leafId;
		this.leafId = branchFromId;
		const entry: BranchSummaryEntry = {
			type: "branch_summary",
			id: generateId(this.byId),
			parentId: branchFromId,
			timestamp: new Date().toISOString(),
			fromId: branchFromId ?? "root",
			summary,
			details,
			usage,
			fromHook,
		};
		try {
			this._appendEntry(entry);
			return entry.id;
		} catch (error) {
			this.leafId = previousLeafId;
			throw error;
		}
	}

	/**
	 * Create a new session file containing only the path from root to the specified leaf.
	 * Useful for extracting a single conversation path from a branched session.
	 * Returns the new session file path, or undefined if not persisting.
	 */
	createBranchedSession(leafId: string): string | undefined {
		const previousSessionFile = this.sessionFile;
		const path = this.getBranch(leafId);
		if (path.length === 0) {
			throw new Error(`Entry ${leafId} not found`);
		}

		// Filter out LabelEntry from path - we'll recreate them from the resolved map.
		// Because labels are real tree entries, later entries can be children of labels;
		// removing labels requires re-chaining the retained path to avoid orphaned subtrees.
		const pathWithoutLabels: SessionEntry[] = [];
		let pathParentId: string | null = null;
		for (const entry of path) {
			if (entry.type === "label") continue;
			pathWithoutLabels.push({ ...entry, parentId: pathParentId });
			pathParentId = entry.id;
		}

		const newSessionId = createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(this.getSessionDir(), `${fileTimestamp}_${newSessionId}.jsonl`);

		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: this.persist ? previousSessionFile : undefined,
		};

		// Collect labels for entries in the path
		const pathEntryIds = new Set(pathWithoutLabels.map((e) => e.id));
		const labelsToWrite: Array<{ targetId: string; label: string; timestamp: string }> = [];
		for (const [targetId, label] of this.labelsById) {
			if (pathEntryIds.has(targetId)) {
				labelsToWrite.push({ targetId, label, timestamp: this.labelTimestampsById.get(targetId)! });
			}
		}

		if (this.persist) {
			// Build label entries
			const lastEntryId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
			let parentId = lastEntryId;
			const labelEntries: LabelEntry[] = [];
			for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
				const labelEntry: LabelEntry = {
					type: "label",
					id: generateId(new Set(pathEntryIds)),
					parentId,
					timestamp: labelTimestamp,
					targetId,
					label,
				};
				pathEntryIds.add(labelEntry.id);
				labelEntries.push(labelEntry);
				parentId = labelEntry.id;
			}

			this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
			this.sessionId = newSessionId;
			this.sessionFile = newSessionFile;
			this._buildIndex();

			// Only write the file now if it contains an assistant message.
			// Otherwise defer to _persist(), which creates the file on the
			// first assistant response, matching the newSession() contract
			// and avoiding the duplicate-header bug when _persist()'s
			// no-assistant guard later resets flushed to false.
			const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message.role === "assistant");
			if (hasAssistant) {
				this._rewriteFile();
				this.flushed = true;
			} else {
				this.flushed = false;
			}

			return newSessionFile;
		}

		// In-memory mode: replace current session with the path + labels
		const labelEntries: LabelEntry[] = [];
		let parentId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
		for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
			const labelEntry: LabelEntry = {
				type: "label",
				id: generateId(new Set([...pathEntryIds, ...labelEntries.map((e) => e.id)])),
				parentId,
				timestamp: labelTimestamp,
				targetId,
				label,
			};
			labelEntries.push(labelEntry);
			parentId = labelEntry.id;
		}
		this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
		this.sessionId = newSessionId;
		this._buildIndex();
		return undefined;
	}

	/**
	 * Create a new session.
	 * @param cwd Working directory (stored in session header)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 */
	static create(cwd: string, sessionDir?: string, options?: NewSessionOptions): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		return new SessionManager(cwd, dir, undefined, true, options);
	}

	/**
	 * Open a specific session file.
	 * @param path Path to session file
	 * @param sessionDir Optional session directory for /new or /branch. If omitted, derives from file's parent.
	 * @param cwdOverride Optional cwd override instead of the session header cwd.
	 */
	static open(path: string, sessionDir?: string, cwdOverride?: string): SessionManager {
		const resolvedPath = resolveSessionFileIdentity(path);
		// If no sessionDir is provided, derive it from the physical file's parent.
		const dir = sessionDir ? normalizePath(sessionDir) : resolve(resolvedPath, "..");
		// _setSessionFile performs one authoritative stable physical-file load and
		// revision-validates any migration commit. Derive cwd from those same entries
		// afterward so alias retargeting cannot mix one file's header with another.
		const manager = new SessionManager(cwdOverride ?? process.cwd(), dir, resolvedPath, true);
		if (cwdOverride === undefined) {
			const header = manager.fileEntries.find((entry) => entry.type === "session") as SessionHeader | undefined;
			if (header) manager.cwd = getSessionHeaderCwd(header) ?? process.cwd();
		}
		return manager;
	}

	/**
	 * Continue the most recent session, or create new if none.
	 * @param cwd Working directory
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 */
	static continueRecent(cwd: string, sessionDir?: string): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const mostRecent = findMostRecentSession(dir, filterCwd ? cwd : undefined);
		if (mostRecent) {
			return new SessionManager(cwd, dir, mostRecent, true);
		}
		return new SessionManager(cwd, dir, undefined, true);
	}

	/** Create an in-memory session (no file persistence) */
	static inMemory(cwd: string = process.cwd(), options?: NewSessionOptions): SessionManager {
		return new SessionManager(cwd, "", undefined, false, options);
	}

	/**
	 * Fork a session from another project directory into the current project.
	 * Creates a new session in the target cwd with the full history from the source session.
	 * @param sourcePath Path to the source session file
	 * @param targetCwd Target working directory (where the new session will be stored)
	 * @param sessionDir Optional session directory. If omitted, uses default for targetCwd.
	 */
	static forkFrom(
		sourcePath: string,
		targetCwd: string,
		sessionDir?: string,
		options?: NewSessionOptions,
	): SessionManager {
		const resolvedSourcePath = resolveSessionFileIdentity(sourcePath);
		const resolvedTargetCwd = resolvePath(targetCwd);
		reconcileMaterializeAliasesBeforeOpen(resolvedSourcePath);
		let sourceEntries: FileEntry[] | undefined;
		for (let attempt = 0; attempt <= SESSION_REVISION_RETRY_ATTEMPTS; attempt++) {
			try {
				sourceEntries = loadStableSessionFile(resolvedSourcePath).entries;
				break;
			} catch (error) {
				if (!(error instanceof SessionFileRevisionMismatchError) || attempt === SESSION_REVISION_RETRY_ATTEMPTS) {
					throw error;
				}
			}
		}
		if (!sourceEntries || sourceEntries.length === 0) {
			throw new Error(`Cannot fork: source session file is empty or invalid: ${resolvedSourcePath}`);
		}

		const sourceHeader = sourceEntries.find((e) => e.type === "session") as SessionHeader | undefined;
		if (!sourceHeader) {
			throw new Error(`Cannot fork: source session has no header: ${resolvedSourcePath}`);
		}
		// The fork header always declares the current format, so migrate the stable
		// source snapshot in memory before copying it. Never rewrite the source file.
		migrateToCurrentVersion(sourceEntries);

		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(resolvedTargetCwd);
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		// Create new session file with new ID but forked content
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		const newSessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(dir, `${fileTimestamp}_${newSessionId}.jsonl`);

		// Write new header pointing to source as parent, with updated cwd
		const newHeader: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: resolvedTargetCwd,
			parentSession: resolvedSourcePath,
		};
		writeFileSync(newSessionFile, `${JSON.stringify(newHeader)}\n`, { flag: "wx" });

		// Copy all non-header entries from source
		for (const entry of sourceEntries) {
			if (entry.type !== "session") {
				appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
			}
		}

		return new SessionManager(resolvedTargetCwd, dir, newSessionFile, true);
	}

	/**
	 * List all sessions for a directory.
	 * @param cwd Working directory (used to compute default session directory)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async list(cwd: string, sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]> {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const resolvedCwd = resolvePath(cwd);
		const sessions = (await listSessionsFromDir(dir, onProgress)).filter(
			(session) => !filterCwd || sessionCwdMatches(session.cwd, resolvedCwd),
		);
		sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
		return sessions;
	}

	/**
	 * List all sessions across all project directories.
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async listAll(onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(
		sessionDirOrOnProgress?: string | SessionListProgress,
		onProgress?: SessionListProgress,
	): Promise<SessionInfo[]> {
		const customSessionDir =
			typeof sessionDirOrOnProgress === "string" ? normalizePath(sessionDirOrOnProgress) : undefined;
		const progress = typeof sessionDirOrOnProgress === "function" ? sessionDirOrOnProgress : onProgress;
		if (customSessionDir) {
			const sessions = await listSessionsFromDir(customSessionDir, progress);
			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		}

		const sessionsDir = getSessionsDir();

		try {
			if (!existsSync(sessionsDir)) {
				return [];
			}
			const entries = await readdir(sessionsDir, { withFileTypes: true });
			const dirs = entries
				.filter((entry) => entry.isDirectory() || entry.isSymbolicLink())
				.map((entry) => join(sessionsDir, entry.name));

			// Count total files first for accurate progress
			let totalFiles = 0;
			const dirFiles: string[][] = [];
			for (const dir of dirs) {
				try {
					const files = (await readdir(dir)).filter((f) => f.endsWith(".jsonl"));
					dirFiles.push(files.map((f) => join(dir, f)));
					totalFiles += files.length;
				} catch {
					dirFiles.push([]);
				}
			}

			// Process all files with progress tracking
			let loaded = 0;
			const sessions: SessionInfo[] = [];
			const allFiles = dirFiles.flat();

			const results = await buildSessionInfosWithConcurrency(allFiles, () => {
				loaded++;
				progress?.(loaded, totalFiles);
			});

			for (const info of results) {
				if (info) {
					sessions.push(info);
				}
			}

			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		} catch {
			return [];
		}
	}
}
